### ISSUE TITLE
Struct PostNotificationV2Resp dose not has BaseResponse message

### ISSUE THREAD

**Issue by machinly** [go-lark/lark#21]
Struct [PostNotificationV2Resp](https://github.com/go-lark/lark/blob/8433f6e27832f6929878a47360e8c585ea8aa918/api_notification.go#L9) dose not has [BaseResponse](https://github.com/go-lark/lark/blob/8433f6e27832f6929878a47360e8c585ea8aa918/api.go#L4).
This hides some error information, which may confuse users.

**Comment by crispgm** [comment]
Lark Open Platform does return this. I think we'd better respect to its field name.

**Comment by machinly** [comment]
BaseResponse will return in bad response.
Success Request:
```shell
curl -X POST -H "Content-Type: application/json" \
 -d '{"msg_type":"interactive","card":{"config":{"wide_screen_mode":true},"elements":[]}}' \
 https://open.feishu.cn/open-apis/bot/v2/hook/xxxxx
```
Success Response:
```json
{
  "Extra":null,
  "StatusCode":0,
  "StatusMessage":"success"
}
```

Bad Request (without elements):
``` shell
curl -X POST -H "Content-Type: application/json" \
 -d '{"msg_type":"interactive","card":{"config":{"wide_screen_mode":true}}}' \
 https://open.feishu.cn/open-apis/bot/v2/hook/xxxxx
```

Bad Resonse:
```json
{
  "code": 11246,
  "data": {},
  "msg": "msg: elements/i18n_elements should not be empty, code: 100000"
}
```

**Comment by crispgm** [comment]
> BaseResponse will return in bad response. Success Request:
> 
> ```shell
> curl -X POST -H "Content-Type: application/json" \
>  -d '{"msg_type":"interactive","card":{"config":{"wide_screen_mode":true},"elements":[]}}' \
>  https://open.feishu.cn/open-apis/bot/v2/hook/xxxxx
> ```
> 
> Success Response:
> 
> ```json
> {
>   "Extra":null,
>   "StatusCode":0,
>   "StatusMessage":"success"
> }
> ```
> 
> Bad Request (without elements):
> 
> ```shell
> curl -X POST -H "Content-Type: application/json" \
>  -d '{"msg_type":"interactive","card":{"config":{"wide_screen_mode":true}}}' \
>  https://open.feishu.cn/open-apis/bot/v2/hook/xxxxx
> ```
> 
> Bad Resonse:
> 
> ```json
> {
>   "code": 11246,
>   "data": {},
>   "msg": "msg: elements/i18n_elements should not be empty, code: 100000"
> }
> ```

Okay, this is weird. So we can basically add `BaseResponse` and it works, but with weird behavior.

**Comment by crispgm** [comment]
Thanks for fixing this.
