### ISSUE TITLE
调用SDK发送消息报错

### ISSUE THREAD

**Issue by xrj1** [go-lark/lark#28]
Error 2022-03-25 06:27:10,985 v1(7) logger.go:26 10.189.53.21 tikcast.union.notice_mint_cron - default - 0 [PostMessage] call failed: unexpect status Bad Request, resp body: {"code":99991661,"msg":"Need a token","data":{}}
调用SDK报错，已经初始化自动授权更新。麻烦同学帮忙看下～飞书：xieruijun

**Comment by crispgm** [comment]
是刚初始化不久的时候发送的对吧？如果是的话先手动调用一次GetTenantAccessTokenInternal(true)
