### ISSUE TITLE
BOE服务调用接口返回tls: first record does not look like a TLS handshake

### ISSUE THREAD

**Issue by 1170300617** [go-lark/lark#32]
报错信息包括：
SendLarkMessage resp:&{Code:0 TenantAppAccessToken: Expire:0}, error: tls: first record does not look like a TLS handshake

GetTenantAccessTokenInternal error: tls: first record does not look like a TLS handshake

但是相同配置我在本地跑单测来发送的时候就可以

**Comment by crispgm** [comment]
@1170300617 boe只有某些域名可以 i18n那边好像不行

另外，字节内部用户可以进交流群反馈。
