### ISSUE TITLE
got error when post message with chat id

### ISSUE THREAD

**Issue by gd0131** [go-lark/lark#64]
![image](https://github.com/go-lark/lark/assets/75298203/7bd4fbb5-ccd2-484d-990d-39ee16372cdc)
when i use PostMessage with BindChatID
![image](https://github.com/go-lark/lark/assets/75298203/0652b273-5c08-4df3-bec5-c660cec0eff5)
got error. the chat id is 7311993580812337180. tenant is bytedance.

**Comment by crispgm** [comment]
@gd0131 the last screenshot is with PSM info, so I removed for you.

**Comment by crispgm** [comment]
@gd0131 It looks like the code you post is okay. What's your `chatID`, is it `oc_xxxxx` or just an int64 number? It should be `oc_xxxxx`.

**Comment by gd0131** [comment]
7311993580812337180. We've been using this kind of chatID（ int64 number） before with no problems. Did something change recently

**Comment by crispgm** [comment]
> 7311993580812337180. We've been using this kind of chatID（ int64 number） before with no problems. Did something change recently

It has changed years ago since the release of Open API v2. The in-house version provides an ID conversion method to convert to this ID to the latest ChatID.

**Comment by gd0131** [comment]
Can you elaborate on how I should accomplish the id conversion，Thank you very much!

**Comment by crispgm** [comment]
> Can you elaborate on how I should accomplish the id conversion，Thank you very much!

There is document in in-house Lark group. But I cannot post here.

**Comment by gd0131** [comment]
I understand if I need to do an id conversion through lark's interface, I've found the interface documentation.
